### ISSUE TITLE
Adding package disables core tree-view package

### ISSUE THREAD

**Issue by SamVerschueren** [ddavison/sublime-tabs#71] opened 2015-03-06 09:34 UTC
By installing this package, the tree-view package of atom is being disabled. Is there a reason for this or is this a bug? It looked like atom was foobar but when I re-enabled the tree-view package it worked correctly.

**Comment by ddavison** [comment] 2015-03-06 14:50
yea, this is by design.  Sublime Tabs will disable this package, and implement it's "own" version.

If you look at the [readme](https://github.com/ddavison/sublime-tabs/blob/master/README.md#to-use), it states:

> Note... This package will replace the Tabs and Tree View package and disable them.

Sublime tabs actually IS the Tabs and Tree View package, but with the added abilities to be like Sublime.

The behavior you are experiencing is intriguing.. can you share a screenshot of the behavior, and let me know which version of sublime-tabs you are using?

**Comment by ismyrnow** [comment] 2015-03-06 15:06
I believe I experienced the same thing. When I added this package, my tree view went away. I followed the instructions in the README and right-clicked on a file, and selected "Reveal in tree view".

It would be less jarring if the plugin could keep the tree view enabled after disabling the default tree-view package (if it was enabled originally).

**Comment by ddavison** [comment] 2015-03-06 15:08
ahhh yes.. I think you might need to restart Atom to actually have things work correctly.  acts kinda weird when it's not on startup

**Comment by SamVerschueren** [comment] 2015-03-07 08:06
I tried restarting atom but didn't work. The only thing that worked was enabling the core tree-view package. By enabling this this sublime-tabs package kept working so not sure why it disables it in the first place.

**Comment by lancekuttner** [comment] 2015-05-15 12:05
Freaked out a bit when it appeared that this had broken Atom altogether. I could not open anything. Please don't disable the Tree View if there is nothing else on offer. Restarting Atom did not help. Thanks ismyrnow - that worked for me.

**Comment by ddavison** [comment] 2015-06-03 12:21
Closing this issue, as sublime-tabs is now in [core](https://github.com/atom/tabs/pull/145)

**Closed by ddavison** 2015-06-03 12:21 UTC
Labels: R-awaiting answer
