### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by simon96aic** [ddavison/sublime-tabs#80] opened 2015-03-24 06:24 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (c:\Users\{username}\AppData\Local\atom\app-0.176.0\resources\app\src\atom.js:53:11)
SublimeTabView.initialize (c:\Users\{username}\.atom\packages\sublime-tabs\lib\sublime-tab-view.coffee:19:9)
```

**Comment by ddavison** [comment] 2015-04-16 12:30
Hey @simon96aic, thanks for opening this! and sorry it took so long to respond, but this turns out to be a duplicate of #53

**Closed by ddavison** 2015-04-16 12:30 UTC
