### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by rslnk** [ddavison/sublime-tabs#108] opened 2015-05-18 14:05 UTC
atom.workspaceView is no longer available. See the [Workspace docs](https://atom.io/docs/api/latest/Workspace) for alternatives. If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.

**Comment by ddavison** [comment] 2015-05-18 14:53
hey @rslnk , thanks for bringing this up.  looks like it's a duplicate of #53

**Closed by ddavison** 2015-05-18 14:53 UTC
Labels: duplicate
