### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by nallie** [ddavison/sublime-tabs#65] opened 2015-02-27 20:19 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
Object.activate (/Users/nallie/.atom/packages/sublime-tabs/lib/sublime-tabs.coffee:39:9)
```

**Comment by ddavison** [comment] 2015-02-27 22:40
thanks for reporting this @nallie ! someone however has beaten you to it :)

closing as dupe of #53

**Closed by ddavison** 2015-02-27 22:40 UTC
