### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by MortalCatalyst** [ddavison/sublime-tabs#88] opened 2015-04-15 00:29 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\sayth\AppData\Local\atom\app-0.191.0\resources\app\src\atom.js:55:13)
Object.activate (C:\Users\sayth\.atom\packages\sublime-tabs\lib\sublime-tabs.coffee:38:9)
```

**Comment by ddavison** [comment] 2015-04-15 10:34
@MortalCatalyst thanks for reporting this! However, it's a dupe of #53. Closing

**Closed by ddavison** 2015-04-15 10:34 UTC
Labels: duplicate
