### ISSUE TITLE
Use the `atom-pane` tag instead of the `pane` class.

### ISSUE THREAD

**Issue by bthusby** [ddavison/sublime-tabs#64] opened 2015-02-21 11:22 UTC
In menus/sublime-tree-view.cson: Use the `atom-pane` tag instead of the `pane` class.

**Comment by ddavison** [comment] 2015-02-21 17:19
this one too, thanks for reporting this!

closing as dupe of #53

**Closed by ddavison** 2015-02-21 17:19 UTC
